name: demoNN
channels:
  - defaults
  - conda-forge
dependencies:
  - h5py=2.10.0
  - jupyter=1.0.0
  - keras=2.3.1
  - matplotlib=3.1.2
  - numpy=1.17.3
  - python=3.7.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - tensorflow=1.13.1

